# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.


title: Titre de l'événement
email: gbif@gbif.fr
description: Description de l'événement

city: Ville # où aura lieu l'événement
insitution: Institution # où se déroulera l'événement 
room: Salle # où se déroulera de l'événement
address: Addresse # où se déroulera l'événement
postcode: Code poste # de la ville où se déroulera l'événement

descriptionLongue: Description de l'événement avec les points principaux (voir <a href="http://formation-ecoscope.gbif.fr" target="_blank"> le site de la formation GBIF France - Ecoscope </a> pour des idées). A noté que les codes <strong> HTML </strong> devront être écrit dans la description longue. <br /> <br /> Les éléments sont a changé dans le fichier _config.yml.
inscription: Les informations sur l'inscription
# Les inscriptions seront ouvertes le 20 avril 2017
# Inscription obligatoire et gratuite dans la limite des places disponibles. Pour cela, nous vous invitons à remplir le formulaire situé dans la partie "Inscription". Afin de finaliser celle-ci, un mail de validation vous sera envoyé par l'équipe du GBIF France.
# Les inscriptions sont closes.

baseurl: "" 
url: "url du site de l'événement" 

twitter_username: gbiffrance
github_username:  gbiffrance

encoding: utf-8

# Build settings
markdown: kramdown
theme: minima

header: img/header_formation_site.png # lien vers l'image de l'entête de la formation

date: Date en mode litérale de la formation #date en mode literral pour être affiché sur la page d'accueil
totalJour: 3 #nombre total de jour de la formation

presentation: none #ajout lorsque le fichier zip regroupant les fichiers présentations
agenda: none #ajout du lien vers l'agenda en .PDF
